server:
  port: 8081
spring:
  application:
    name: ai-server
  profiles:
    active: dev
  ai:
    openai:
      api-key: api_key
      model: gpt-4.1
      embedding:
        enabled: true
        options:
          model: text-embedding-ada-002

    mcp:
      client:
        stdio:
          connections:
            notionApi:
              command: "C:\\Program Files\\nodejs\\npx.cmd"
              args:
                - "-y"
                - "@notionhq/notion-mcp-server"
              env:
                OPENAPI_MCP_HEADERS: "{\"Authorization\": \"Bearer key\", \"Notion-Version\": \"2022-06-28\"}"
      toolcallback:
        enabled: true

eureka:
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server1:8761/eureka,http://discovery-server2:8762/eureka,http://discovery-server3:8763/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      enabled: true
      show-details: always
      show-components: always
    tracing:
      sampling:
        probability: 1.0
